### ISSUE TITLE
Not able to install via composer

### ISSUE THREAD

**Issue by gusilva** [yguedidi/global-functions-mocker#2]
Composer error msg:

"Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package yguedidi/global-functions-mocker could not be found in any version, there may be a typo in the package name.

Potential causes:
- A typo in the package name
- The package is not available in a stable-enough version according to your minimum-stability setting
  see https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion for more details.

Read https://getcomposer.org/doc/articles/troubleshooting.md for further common problems."

**Comment by yguedidi** [comment]
@gusilva Thanks for reporting this.

The issue was that the package was not referenced in Packagist, because I abandoned it. I no more think that mocking global functions is a good practice (and I also not have the time for now to maintain it)

It now should be fixed, I register this package on packagist and mark it as abandoned for now. If you really want to use it, you should install it with the dev stability flag:  
`"yguedidi/global-functions-mocker": "*@dev"`.

Thanks again.

**Comment by gusilva** [comment]
I was looking for a package to test a method that call to a global function (exec()). I would like to mock the result of this function. Do you have another better way to test it? For example, I want to run the command "stty" but it is not installed yet, however I want to check the return value. Because of this I have two scenarios: 1 - command execute OK, return value 0. 2 - command fail, return value different from 0. 
The function is like this:
function hasStty() {
  exec("stty --version >  > /dev/null 2>&1", $output, $return_val);
  return ($return_val === 0) ? true : false;
}

Is there another better way to test it?

By the way, thanks!

**Comment by yguedidi** [comment]
I'll suggest you to use [symfony/process](https://github.com/symfony/Process) component instead of using `exec()`, then you can mock the `Process` class

**Comment by gusilva** [comment]
Awesome!! thks!
